version: '3.7'

services:

    scrapyd:
        build:
            context: ./scrapyd
            args:
                - USERNAME=user
                - PASSWORD=pass
        init: true
        restart: always
        ports:
            - 6800:6800
        environment:
            - DATA_DIR=/var/lib/scrapyd
            - TZ=America/Sao_Paulo
        volumes:
            - scrapyd_data:/var/lib/scrapyd
        networks:
            - scrapyd_network

    scrapydweb:
        build: ./scrapydweb
        init: true
        restart: always
        ports:
            - 5000:5000
        environment:
            - USERNAME=user
            - PASSWORD=pass
            - SCRAPYD_SERVERS=user:pass@scrapyd:6800
            - LOCAL_SCRAPYD_SERVER=scrapyd:6800
            - LOCAL_SCRAPYD_LOGS_DIR=/var/lib/scrapyd/logs
            - TELNET_CONSOLE_HOST=scrapyd
            - DATA_PATH=/var/lib/scrapydweb/data
            - TZ=America/Sao_Paulo
        volumes:
            - scrapydweb_data:/var/lib/scrapydweb/data
            - scrapyd_data:/var/lib/scrapyd
        networks:
            - scrapyd_network
        depends_on:
            - scrapyd

volumes:
    scrapyd_data:
    scrapydweb_data:

networks:
    scrapyd_network:
        driver: bridge
