version: '3.7'

services:

    scrapyd:
        build:
            context: ./scrapyd
            args:
                - USERNAME=ivan
                - PASSWORD=qconcursos
        restart: always
        container_name: scrapyd
        ports:
            - 6800:6800
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - scrapyd_data:/var/lib/scrapyd/data
        networks:
            - scrapyd_network

    scrapydweb:
        build:
            context: ./scrapydweb
            args:
                - USERNAME=ivan
                - PASSWORD=qconcursos
                - SCRAPYD_SERVERS=ivan:qconcursos@scrapyd:6800
                - DATA_PATH=/var/lib/scrapydweb/data
        restart: always
        ports:
            - 5000:5000
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - scrapydweb_data:/var/lib/scrapydweb/data
        networks:
            - scrapyd_network
        depends_on:
            - scrapyd

volumes:
    scrapyd_data:
    scrapydweb_data:

networks:
    scrapyd_network:
#        driver: bridge
